#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = 'srcery'
colorscheme_bg = 'dark'
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = 'arrow'
statusline_iseparator = 'arrow'
enable_tabline_filetype_icon = false
enable_statusline_mode = true
enable_statusline_date = true
enable_statusline_time = true
statusline_unicode_symbols = false
buffer_index_type = 4
default_indent = 8
expand_tab = true

windows_leader = ''
filemanager = 'nerdtree'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'gtags'

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[layers]]
name = 'ui'

[[layers]]
name = 'incsearch'

[[layers]]
name = 'git'
git_plugin = 'fugitive'

[[layers]]
name = 'core'
filetree_show_hidden = true

[[layers]]
name = 'core#statusline'
